move_manager_node:
  ros__parameters:    
    # Command topics
    command_topic: "/seed_pdt_drone/command"
    status_topic: "/move_manager/status"
    
    # Path planner interface
    path_planner_goal_topic: "/move_base_simple/goal"
    path_planner_status_topic: "/path_planner/status"
    
    # Trajectory interpolator interface  
    traj_interp_path_topic: "/trajectory_path"
    traj_interp_status_topic: "/trajectory_interpolator/status"
    
    # Path planning output
    planned_path_topic: "/trajectory_path"
    
    # Sensor input
    odometry_topic: "/px4/odometry/out"
    joy_topic: "/joy"
    
    # Flight parameters
    takeoff_altitude: 1.5  # meters
    landing_altitude: -0.5  # meters

    # Simulation parameters
    simulation: false  # Set to true for simulation mode with TF publishing

    fixed_frame: "map"  # Fixed frame for TF in simulation mode
    reference_frame: "drone/map"  # Reference frame for all topics
    child_frame: "odom"  # Drone's child frame for odometry
    base_link: "base_link"  # Drone's base link frame
